version: '3.4'

services:
  accountservice:
    image: accountservice
    expose:
     - 3000
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
